name: learn-github-actions
on: [push]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is next.js"
      - uses: actions/checkout@v4
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
