name: recollect-web-ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Instal dependencies
        run: pnpm i --frozen-lockfile

      - name: Run test
        run: pnpm test
